# Generated by Django 3.0 on 2019-12-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('symbol', models.CharField(max_length=3)),
                ('est_name', models.TextField()),
                ('name', models.TextField()),
                ('group', models.IntegerField()),
                ('period', models.IntegerField()),
                ('block', models.CharField(max_length=3)),
                ('protons', models.IntegerField()),
                ('neutrons', models.IntegerField()),
                ('electrons', models.IntegerField()),
                ('mass', models.FloatField()),
                ('eleneg', models.FloatField()),
                ('tboil', models.FloatField()),
                ('tmelt', models.FloatField()),
                ('density', models.FloatField()),
                ('oxistates', models.TextField()),
                ('atmrad', models.FloatField()),
            ],
        ),
    ]
